---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - name: 'oxlorg.nftables'
    src: 'git+https://github.com/O-X-L/ansible-role-nftables'

  - name: 'oxlorg.linux_users'
    src: 'git+https://github.com/O-X-L/ansible-role-linux-users'

  - name: 'oxlorg.linux_networking'
    src: 'git+https://github.com/O-X-L/ansible-role-linux-networking'

collections:
  - 'community.general'
  - 'ansible.posix'
